Pedro/create groups route
LaurierCS/Pod4F23 pull request #13
Opened 2023-10-25 02:31 UTC by itsPedro231

I created the groups route. You can POST a new group and GET all groups or a group by id. The Group model only has a field for name.

- Get group by ID: GET api/groups/{id}/
- Create a new group: POST api/groups/

- Only need a group_name to POST a new group
      - Using a browser: {"group_name": "groupname"}
      - Using cURL: curl -X POST -d '{"group_name":"groupname"}' -H "Content-Type: application/json" http://127.0.0.1:8000/groups/

Also, I'm not sure if i was supposed to add the db migration files, but added them anyways.

2023-10-25 22:03 UTC, pabloj2001 requested changes

2023-10-25 22:03 UTC, pabloj2001 commented on api/optimeet/groups/views.py
> +    if request.method == 'GET':
We're not going to want to return all groups, since not every user is going to be a part of every group. We would usually want to filter the groups based on the user, but since we're not implementing group history right now, we don't need to return all groups that a user is a part of either.

2023-10-25 22:03 UTC, pabloj2001 commented on api/optimeet/groups/views.py
> +@api_view(['GET', 'POST'])
Since right now we're not implementing POST for a specific group, let's remove it completely, since we want an error to return when someone tries to make a POST request to this endpoint, since it doesn't exist. Perhaps in the future we can add it back in if we implement editing a group's settings.

2023-10-25 22:03 UTC, pabloj2001 commented on api/optimeet/optimeet/urls.py
> +    #path("activities/", include("activities.urls")),
Please remove for now since it doesn't have to do with the issue this pull request is trying to solve.

2023-10-25 22:04 UTC, pabloj2001 reviewed
Good job on these routes! Left a few comments

2023-10-25 22:38 UTC, itsPedro231 commented on api/optimeet/groups/views.py
> +    if request.method == 'GET':
done

2023-10-25 22:38 UTC, itsPedro231 commented on api/optimeet/groups/views.py
> +@api_view(['GET', 'POST'])
done

2023-10-25 22:38 UTC, itsPedro231 commented on api/optimeet/optimeet/urls.py
> +    #path("activities/", include("activities.urls")),
done

2023-10-25 23:06 UTC, pabloj2001 submitted a review, later dismissed
LGTM! 👍

2023-10-26 19:28 UTC, pabloj2001 approved these changes, later dismissed
Good catch on that missing param!

2023-10-27 20:34 UTC, pabloj2001 submitted a review, later dismissed

2023-10-28 15:44 UTC, ctlchan submitted a review, later dismissed
Looks good!

2023-10-28 15:58 UTC, ctlchan approved these changes

2023-10-28 15:58 UTC, pabloj2001 approved these changes

2023-10-28 15:59 UTC, merged