Locationpage
LaurierCS/Pod4F23 pull request #28
Opened 2023-11-07 19:16 UTC by marissa-anj

@ctlchan Not entirely sure where you want to link this page after the google auth, but use the LocationMain.jsx as the main location page link

2023-11-08 00:35 UTC, pabloj2001 requested changes
Good job on this PR! Left a few comments for things we should address

2023-11-08 00:35 UTC, pabloj2001 commented on web/meetup-facilitator/README.md
> +npm install react-places-autocomplete
If you run these installs once, they should get saved to `package.json` and be able to all be installed at once by using `npm install` in the future. There shouldn't be a need to install them individually every time.

2023-11-08 00:35 UTC, pabloj2001 commented on web/meetup-facilitator/src/components/LocationPage/AddressInput.jsx
> +    googleMapsApiKey: 'API KEY HERE', // Replace with Google Maps API key
Could you replace this with an environment variable? It would look something like this:
```
import.meta.env.VITE_CLIENT_ID
```
We can then add our Google API Key to the `.env` file in the root directory as a key-value pair.

2023-11-08 00:35 UTC, pabloj2001 commented on web/meetup-facilitator/README.md
> +npm install --save react-google-maps
This library seems to be deprecated and unmaintained; I wasn't able to install it. It looks like someone made a new version `@react-google-maps/api`. Let's use that one instead!

2023-11-15 02:21 UTC, pabloj2001 requested changes

2023-11-15 02:21 UTC, pabloj2001 commented on web/meetup-facilitator/README.md
> +npm install react-places-autocomplete
This should no longer be necessary since the packages are all in `package.json`

2023-11-15 02:21 UTC, pabloj2001 commented on web/meetup-facilitator/src/pages/Home.jsx
> +    // })
Please put back after testing!

2023-11-15 02:21 UTC, pabloj2001 commented on web/meetup-facilitator/src/components/AddressInput.jsx
> +    googleMapsApiKey: import.meta.env.API_KEY, // Add API_KEY to .env
Let's rename `API_KEY` to `VITE_GOOGLE_API_KEY` to be more descriptive

2023-11-15 02:33 UTC, ctlchan approved these changes, later dismissed

2023-11-17 02:57 UTC, pabloj2001 requested changes
Gj on this PR, let's ship it! I resolved and commited a merge conflict so you wouldn't have to get another approval later.

2023-11-17 02:58 UTC, pabloj2001 approved these changes
Gj on this PR, let's ship it! I resolved and commited a merge conflict so you wouldn't have to get another approval later.

2023-11-17 03:36 UTC, ctlchan approved these changes

2023-11-18 02:04 UTC, merged