TimeSelectionPage
LaurierCS/Pod4F23 pull request #29
Opened 2023-11-07 19:30 UTC by marissa-anj

the links may have to be reconfigured 

i updated the readme which may have conflicts with the pull req i just sent to for location page

2023-11-09 16:48 UTC, ctlchan requested changes
Can you commit the updated package.json just so that everything needed can be installed by running `npm install` once? 

Other than that, everything looks good. The link can be addressed by adding the following routes in App.jsx:

`<Route path='/time' element={<TimeMain/>} />`
`Route path='TimeHour/' element={<TimeHour/>} />`

2023-11-14 18:37 UTC, ctlchan submitted a review, later dismissed

2023-11-15 01:13 UTC, pabloj2001 requested changes
GJ only some small changes to make

2023-11-15 01:13 UTC, pabloj2001 commented on web/meetup-facilitator/README.md
> +npm install react-multi-date-picker
Let's install this separately so it gets added to `package.json`

2023-11-15 01:13 UTC, pabloj2001 commented on web/meetup-facilitator/src/pages/Home.jsx
> +    // })
Please revert changes after you're done testing!

2023-11-15 01:13 UTC, pabloj2001 commented on web/meetup-facilitator/src/Timepage/TimeHour.jsx
> +  console.log("TimeHour rendered");
Let's remove debug console logs, since we don't want to leak what's going on in the background once we're in production

2023-11-15 02:32 UTC, pabloj2001 submitted a review, later dismissed
LGTM! 👍

2023-11-15 02:33 UTC, pabloj2001 submitted a review, later dismissed

2023-11-15 02:33 UTC, ctlchan submitted a review, later dismissed

2023-11-15 02:34 UTC, pabloj2001 approved these changes

2023-11-15 02:36 UTC, ctlchan approved these changes

2023-11-15 02:37 UTC, merged