Chris/create join group
LaurierCS/Pod4F23 pull request #43
Opened 2023-11-26 00:01 UTC by ctlchan

Implemented the Join page. Made it so that you need a `group_id` in the URL that is valid, or else you are redirected to the home page; did the same for the preferences page. Also added a default route just so non-existent routes can redirect. 

I wanted to also make the Home page redirect to preferences after successfully creating a group, but I will address that in a later commit to the branch (the `group_id` should be in the response I think?)

2023-11-26 00:52 UTC, ctlchan commented
Implemented redirect to preferences after successfully creating a group

2023-11-26 18:56 UTC, pabloj2001 requested changes
Good job! Only a few minor changes from me

2023-11-26 18:56 UTC, pabloj2001 commented on web/meetup-facilitator/src/App.jsx
> +          <Route path='join/:group_id' element={<Join/>}/>
Let's start `join` with a `/` to keep it consistent.

2023-11-26 18:56 UTC, pabloj2001 commented on web/meetup-facilitator/src/pages/Home.jsx
> +            if (Object.keys(json).length > 1)
Let's check that `json` explicitly contains `group_id`

2023-11-27 01:25 UTC, pabloj2001 approved these changes
LGTM!

2023-11-27 01:39 UTC, marissa-anj approved these changes

2023-11-27 01:45 UTC, merged